# This rule is not used by the project gateway itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to gateway.githedgehog.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/managed-by: kustomize
  name: vpcinfo-viewer-role
rules:
- apiGroups:
  - gateway.githedgehog.com
  resources:
  - vpcinfos
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.githedgehog.com
  resources:
  - vpcinfos/status
  verbs:
  - get
